<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <Platforms>x64</Platforms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BinaryExtensionsDotNET" Version="1.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Security.Permissions" Version="8.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
    <PackageReference Include="Yarhl" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HActLib">
      <HintPath>HActLib.dll</HintPath>
    </Reference>
    <Reference Include="LibARMP">
      <HintPath>LibARMP.dll</HintPath>
    </Reference>
    <Reference Include="PIBLib">
      <HintPath>..\..\..\PIBLib\bin\x64\Release\net6.0\PIBLib.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
