<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ElvisCommand</RootNamespace>
    <AssemblyName>ElvisCommand</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;YLAD Debug;YLAD Release</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'YLAD Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\YLAD Debug\</OutputPath>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'YLAD Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\YLAD Debug\</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'YLAD Release|AnyCPU'">
    <OutputPath>bin\YLAD Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'YLAD Release|x64'">
    <OutputPath>bin\x64\YLAD Release\</OutputPath>
  </PropertyGroup>

</Project>