<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>KiryuBalanceAddon</RootNamespace>
    <AssemblyName>Kiryu Balance Addon</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;Infinite Wealth Debug;Infinite Wealth Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Y7Internal.NET\DELibrary.NET\DELibrary.NET.csproj" />
  </ItemGroup>
</Project>